#!/bin/sh

echo
gstat --all -1 | awk '
{
    n = split($0, a, " ", b)
	if (a[1] == "Hostname") a[1] = sprintf("%-20s", a[1])
	if (n == 12) a[1] = sprintf("%15s", a[1])
	if (n == 16) a[1] = sprintf("%-10s", a[1])
    line = b[0]
    for (i = 1; i <= n; i++)
        line=(line a[i] b[i])
	if (n == 16) {
		c = a[9]+0
        if (c < a[2]/4) {
            print "\033[1;32m"line"\033[0m"
        } else if (c < a[2]/2) {
            print "\033[1;33m"line"\033[0m"
        } else {
            print "\033[1;31m"line"\033[0m"
        }
    } else {
        print line
    }
}'
echo
